version: '3.2'
services:
  stock-api-service1:
    build: .
    tty: true
    volumes:
      - '/usr/app/src'

  stock-api-service2:
    build: .
    tty: true
    volumes:
      - '/usr/app/src'

  stock-api-service3:
    build: .
    tty: true
    volumes:
      - '/usr/app/src'


  stock-api-service4:
    build: .
    tty: true
    volumes:
      - '/usr/app/src'

  proxyserver:
    build: ./proxyserver
    tty: true
    links:
      - stock-api-service1
      - stock-api-service2
      - stock-api-service3
      - stock-api-service4
    ports:
      - '8080:80'
